### ISSUE TITLE
Potential rationalization of bitwise operations

### ISSUE THREAD

**Issue by bobbinth** [maticnetwork/miden#120]
As I learned from @dlubarov, it is possible to emulate bitwise `AND`, `OR`, `XOR` operations using just one of these operations and some filed element operations. Specifically, assuming we have access to `AND`, the other two can be described as:

```
XOR(x, y) = x + y - 2 * AND(x, y)
OR(x, y) = x + y - AND(x, y)
```

Thus, we could eliminate 2 out of the following 3 operations: `U32AND`, `U32OR`, `U32XOR`. This wouldn't save us much in terms of trace length or constraint complexity, but it would allow us to remove 2 instructions from the instruction set if needed.

If we do go this route, it probably makes sense to keep `XOR` operation as the one natively supported by the VM and emulate the other two through it.

**Comment by dlubarov** [comment]
I got the idea from @nbgl by the way, who mentioned similar formulas in Hacker's Delight.

Some proof sketches:

> `x + y = AND(x, y) + OR(x, y)`

We can manually verify that this holds for single-bit `x`, `y`; then

    x + y = \sum_i 2^i (x_i + y_i)
          = \sum_i 2^i (AND(x_i, y_i) + OR(x_i, y_i))
          = \sum_i 2^i AND(x_i, y_i) + \sum_i 2^i OR(x_i, y_i)
          = AND(x, y) + OR(x, y)

> `x + y = XOR(x, y) + 2 * AND(x, y)`

The above approach works, but we can also view this as calculating `x + y` with grade school addition. `XOR(x, y)` represents intermediate sums without carries, while `2 * AND(x, y)` represents carry bits, shifted one digit to the left as per the algorithm.

> `NOT(x) = -x - 1`

`-x` here means `2^l - x`[^1], where `l` is our bit length. So we can rewrite this as `NOT(x) = MAX - x`, where `MAX = 2^l - 1`. Since `MAX` consists of all 1 bits, no borrows occur in `MAX - x`, so the subtraction can be done bitwise, giving `NOT(x)`.

[^1]: This is arithmetic mod `2^l`, so `-0 = 2^l - 0 = 2^l = 0`.

**Comment by bobbinth** [comment]
Superseded by #358.
