### ISSUE TITLE
Script compilation time

### ISSUE THREAD

**Issue by bobbinth** [maticnetwork/miden#153]
It seems like compiling large scripts (e.g., sha256 in the standard library) takes quite a bit of time. This is especially apparent when running tests in debug mode (which is the default). For example, sha256 tests takes over 40 seconds to complete, and this is likely driven by the assembler. When running tests in release mode, the situation is better - i.e., under 1 second - but still.

We should investigate what is the bottleneck in the assembler and figure out how to address this. My guess is that a big part of this is driven by computing program hash, but would be good to confirm this.

**Comment by itzmeanjan** [comment]
> My guess is that a big part of this is driven by computing program hash, but would be good to confirm this.

You mean while constructing Merklised Syntax Tree of assembly program, is it ?

**Comment by bobbinth** [comment]
Right. Overall, even for 3K instructions, building the MAST shouldn't require more than 100 or so invocations of the hash function - so, there must be some inefficiency somewhere.

**Comment by itzmeanjan** [comment]
And we're using rescue prime as hash function, is it ?

**Comment by bobbinth** [comment]
> And we're using rescue prime as hash function, is it ?

correct.

**Comment by willyrgf** [comment]
I would love to work in this issue if no one is.

**Comment by bobbinth** [comment]
Awesome! I'll assign this to you. Thank you!

**Comment by willyrgf** [comment]
@bobbinth - Debugging the code trying to understand where is the most expensive part of it, I found somethings and I've some questions:

The most expensive part of the executions seems to be in the first loop of [`combine_blocks()`](https://github.com/maticnetwork/miden/blob/ca1cfa7dad59cdb4998e42e4c71605d30c85cf87/assembly/src/parsers/blocks.rs#L256) more specific in the hash of the batch groups inside of [`batch_ops()`](https://github.com/maticnetwork/miden/blob/next/core/src/program/blocks/span_block.rs#L245).
- The cost of the `hasher::hash_elements(flatten_slice_elements(&batch_groups))` seems to be linear for the length of the `batch_groups` (like, length 575 cost 485ms, length 337 cost 295ms) , is this what is expected?
- Inside of the [`combine_blocks()`](https://github.com/maticnetwork/miden/blob/ca1cfa7dad59cdb4998e42e4c71605d30c85cf87/assembly/src/parsers/blocks.rs#L256) we're calling `batch_ops()` for each span with `last_span.append(span)` and some `blocks` of the `combine_blocks()` have 200 or 300 of spans in the block and this is case is very expensive because of the linear cost per span mentioned above. Decompose `blocks` in two types of blocks (span blocks and non-span blocks), run `batch_ops()` just one time for all "span blocks" and recompose this two types in the correct positions, is that a possible solution for it? 
- Do you think that the difference of 40s to 1s from `debug` to `release` versions is that a problem? Or the release version expending 1s is a problem? I think some part of the difference can be the optimization (like debug assertions disabled) that happens in the `release version`, that make sense?

**Comment by bobbinth** [comment]
@willyrgf - thank you so much for looking into this! To answer your questions:

> The cost of the `hasher::hash_elements(flatten_slice_elements(&batch_groups))` seems to be linear for the length of the `batch_groups` (like, length 575 cost 485ms, length 337 cost 295ms) , is this what is expected?

Linear cost is to be expected: `hash_elements()` is linear in the number of elements to be hashed (and each batch group contains 8 elements). Regarding the exact numbers you show: are these in debug or release mode? If in release mode, these are quite surprising: hashing 1000 elements (or ~125 groups) shouldn't take more than 1 ms.

> and some `blocks` of the `combine_blocks()` have 200 or 300 of spans in the block

Do you mean 200 or 300 ops in a span? or spans in a block? If the latter, then it is rather surprising, but if the former, it is OK. Some spans could have hundreds (or even thousands) of ops in them.

> Or the release version expending 1s is a problem?

I think we should create a benchmark (e.g., using Criterion) for script compilation time on an example of a moderately complex program (e.g. sha256) and see how it performs. My expectation is that compiling such programs shouldn't take more than a few milliseconds in release mode (benchmarks are usually run in release mode). So, if we see results which are very different from this, we can try to see what can be optimized.

In terms of potential places to optimize, I think we'll get the biggest result by trying to minimize the number of times we need to call `hash_elements()`. With the current structure, we call it many times while we are building the program tree, and my suspicion is that many of these calls are unnecessary. An ideal way would be to build the tree, and then compute hash of all blocks - but I'm not sure how to do this yet.

**Comment by willyrgf** [comment]
Hi @bobbinth - sorry for that, but I will need to focus my time on other new things. Can you unassign me here? If somehow I found time and it's still available I'll send a PR.

**Comment by bobbinth** [comment]
No worries! Thank you @willyrgf

**Comment by 0xKanekiKen** [comment]
@bobbinth: I'd love to pick it up from here.

**Comment by 0xKanekiKen** [comment]
@bobbinth: On my machine with AMD Ryzen 5 3550H running Pop!_OS 22.04 LTS, the sha256 compilation benchmark is taking 
`time:   [2.8630 s 2.8750 s 2.8874 s]`

**Comment by bobbinth** [comment]
Closed by #250
