### ISSUE TITLE
Advice Set Addition - merkle tree witness / sparse merkle tree witness

### ISSUE THREAD

**Issue by frisitano** [maticnetwork/miden#325]
When providing data to miden via (sparse) markle trees it is not necessary to provide the full data set but only the witness associated with data that is read or modified.  Hence, it will be useful to introduce additional advice sets for merkle tree witness and spare merkle tree witnesses.  This will reduce the memory overhead.  What do you think?

**Comment by bobbinth** [comment]
Currently we have 3 different [advice sets](https://github.com/maticnetwork/miden/blob/next/core/src/inputs/advice/mod.rs#L16):

1. Merkle tree - where we need to provide all leaf nodes.
2. Sparse Merkle tree - where we need to provide only non-zero leaf nodes.
3. Merkle path set - where we can provide 1 or more Merkle paths agains some tree (either sparse or otherwise).

I believe the situation you described is covered by the last point above. But let me know if I misunderstood.

**Comment by frisitano** [comment]
Ahh yes, I hadn't fully appreciated the structure of the Merkle path set.  Nice!
