### ISSUE TITLE
Basic example failing

### ISSUE THREAD

**Issue by zachanon** [maticnetwork/miden#371]
Following along [here](https://github.com/maticnetwork/miden/tree/main/miden#proof-generation-example) I made a test file like so:

```
use air::ProofOptions;
use assembly::Assembler;
use vm_core::ProgramInputs;

#[test]
fn test_sum() {
    let assembler = Assembler::default();

    let program = assembler.compile("begin push.3 push.5 add end").unwrap();

    let (outputs, proof) = prover::prove(
        &program,
        &ProgramInputs::none(),
        1,
        &ProofOptions::default(),
    )
    .unwrap();
}
```

Then run:
`cargo test --package miden --lib -- example::test_sum --exact --nocapture`

That fails with message:
```
running 1 test
thread 'example::test_sum' panicked at 'assertion failed: `(left == right)`
  left: `QuadExtension(BaseElement(1578973807784922084), BaseElement(3665351948439021011))`,
 right: `QuadExtension(BaseElement(1), BaseElement(0))`'
 ```
 
 Not sure what could be going wrong. Am I missing some build options on cargo?

**Comment by bobbinth** [comment]
Most likely, this is due to the restriction that number of items on the stack at the end of program execution must be exactly 16 (described [here](https://maticnetwork.github.io/miden/intro/overview.html#stack-depth-restrictions)). A way to fix this would be to add `swap drop` at the end. So, the program would look like so:
```
begin push.3 push.5 add swap drop end
```
This way, the result would still be at the top of the stack, but we'll get rid of the extra item and stack depth at the end would be 16.

This is a very unintuitive and annoying restriction, and we'll get rid of it once #347 is addressed.

**Comment by zachanon** [comment]
Late getting back, but that indeed fixed it. Thanks. Fascinating project thanks for the work
