### ISSUE TITLE
Outdated Documnetation Site

### ISSUE THREAD

**Issue by mariari** [maticnetwork/miden#410]
Although the [documentation on github gives the correct instructions](https://github.com/maticnetwork/miden/blob/main/docs/src/user_docs/assembly/io_operations.md#non-deterministic-inputs), the [actual doc site which is linked](https://maticnetwork.github.io/miden/user_docs/assembly/io_operations.html) gives the wrong instructions.

It would be nice for the docs site to be updated with the proper assembly instructions.

On an unrelated note/question: has the cost model of cycles changed, it seems to be removed from the documentation it seemed like a good heuristic to understand the cost of the system.

**Comment by bobbinth** [comment]
So, the issue is that docs in the main branch on Github are for v0.2 release while docs on the [site](https://maticnetwork.github.io/miden/intro/main.html) are for the `next` branch. So, if you are using v0.2 (or the `main`) branch - Github docs are the relevant ones, but if you are using `next` branch, then the site docs are the relevant ones.

I don't think we explain this anywhere, and I can see how this can be confusing. We'll need to think how to make this more clear and maybe link to the right docs from the right branch.

**Comment by Dominik1999** [comment]
We now have two documentations:

- Stable v.0.2.0 release under https://wiki.polygon.technology/docs/miden/intro/main/
- Next branch release under https://miden.polygon.technology/

I will create a PR to change our README to let everyone know.
