### ISSUE TITLE
Serialization of Miden assembly libraries

### ISSUE THREAD

**Issue by bobbinth** [maticnetwork/miden#469]
Currently, we have only a single library - `stdlib`. When we serialize AST structure for the library, we put it directly into a Rust file (`asm.rs`). As we make the structure more general, it would probably be a good idea to have a stand-alone format which is language independent.

We can probably do something as simple as serialize ASTs (similar to how we do it now) into a separate binary file, and then refer to this file from `asm.rs`. The binary file should probably include the following data:

* Root namespace - e.g., for the standard library this would be `std`.
* Version - e.g., `v0.1`, `v0.2` etc.
* A map of serialized `ModuleAst` structs keyed by module path (relative to root namespace).

One open question: what should be the extension of this file. Two options come to mind:
1. `.mlib` - Miden Library.
2. `.mamb` - Miden Assembly Module Bundle (or Miden Assembly Module Binary).

I prefer the second option - but open to other suggestions.

**Comment by vlopes11** [comment]
Preliminary suggestion:

- A possible name is `.mobj` that recalls the idea of compiling+linking. We compile the code into AST, and then we link it into a CodeBlock/Program.

I'm using the `.mamb` meanwhile; if we opt to rename, shouldn't be a major issue.

Currently doing:

- Creating a `assembly/src/mamb` module that will contain a bytes serializable structure with the proposed format, being: Root namespace, version, Map Path (including namespace) |-> ModuleAst. I think its more natural if we always use absolute paths everywhere because it will simplify the compilation process (i.e. we don't need to evaluate relative paths). wdyt @bobbinth ?
- This structure will be created given a root namespace, and a directory of `.masm` files. Note: this process will ignore files of different extension
- Will allow the serialization of the map into a target directory. It will create a `<root namespace>.mamb` file with the bytes of the bundle.

**Comment by vlopes11** [comment]
As possible improvement, when compiling, we provide a directory that will contain the `mamb` files. As the root namespaces are required, we deserialize the binary files and provide the modules to the user

**Comment by vlopes11** [comment]
Closed by #584
